name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js node20
      uses: actions/setup-node@v2
      with:
        node-version: 'node16'
        cache: 'npm'
    - run: npm test
